config/routes.rb
Rails.application.routes.draw do
  root to: 'placas#index'
  resources :placas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/placa.rb
class Placa < ApplicationRecord
  self.table_name = 'placas_carro'


  validates :placa, :proprietario, :modelo, :ano, presence: { message: "Deve ser preenchido"}
  validates :placa, format: { with: /^[a-zA-Z]{3}[0-9]{4}$/, message: "Placa inválida (aaa0000)" }
  validates :ano, length: { is: 4, message: "Apenas 4 números (yyyy)" }
end

app/models/placa_carro.rb
class PlacaCarro < ApplicationRecord
  self.table_name = 'placas_carro'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/placas_controller.rb
class PlacasController < ApplicationController

  def index
    @registros = Placa.all
  end

  def edit
    @placa = Placa.find(params[:id])
  end

  def update
    @placa = Placa.find(params[:id])
    if @placa.update(placa_params)
      redirect_to placas_path
    else
      flash.now[:alert] = "Todos campos devem ser preenchidos corretamente"
      render(:edit)
    end
  end

  def new
    @placa = Placa.new
  end

  def create
    @placa = Placa.new(placa_params)
    if @placa.save
      redirect_to placas_path
    else
      flash.now[:alert] = "Todos campos devem ser preenchidos corretamente"
      render(:new)
    end
  end

  def destroy
    Placa.delete(params[:id])
    redirect_to placas_path
  end

  private

  def placa_params
    params.require(:placa).permit(:placa,:proprietario,:modelo,:ano)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaPlacas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/placas/_form.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>

  <%= form_with model: @placa, local: true do |form| %>

  <%= link_to 'Voltar para tela inicial', root_path, class:'btn btn-primary buttons-success' %>

    <div class="form-group col-sm-10">
      <%= form.label :placa, 'Placa: (Ex: aaa0000)', style:'font-size: 20px'%>
      <%= form.text_field :placa, class: "form-control #{ 'is-invalid' if @placa.errors.include?(:placa)}" %>

      <% if @placa.errors.include?(:placa) %>
        <div class="invalid-feedback" style="display:block">
          <%= @placa.errors.messages[:placa].first %>
        </div>
      <% end %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.label :proprietario, 'Proprietário:', style:'font-size: 20px'%>
      <%= form.text_field :proprietario, class:'form-control'%>
    </div>
    <div class="form-group col-sm-10">
      <%= form.label :modelo, 'Modelo:', style:'font-size: 20px'%>
      <%= form.text_field :modelo, class:'form-control'%> 
    </div>
    <div class="form-group has-validation col-sm-10">
      <%= form.label :ano, 'Ano: (Ex: 2010)', style:'font-size: 20px'%>
      <%= form.text_field :ano, class:"form-control #{ 'is-invalid' if @placa.errors.include?(:ano)}"%>

          <% if  @placa.errors.include?(:ano) %>
        <div class="invalid-feedback" style="display:block">
          <%= @placa.errors.messages[:ano].first %>
        </div>
      <% end %>
    </div>

  <%= form.submit 'Criar novo registro', class:'btn btn-success buttons-success'%> 
  <%end%>
</div>

app/views/placas/edit.html.erb
<%= render 'form' %>

app/views/placas/index.html.erb
<h1 class="m-3"> Bem vindo!!! </h1>
<h2 class="m-3"> Cadastro de Placas de Carros </h2>

</br></br>

<%= link_to 'Adicionar novos registros', new_placa_path, class: 'btn btn-success float-right m-3' %>

  <table class="table table-striped">
    <div class="table-responsive">
    <thead>
      <tr>
        <th scope="col">Placa</th>
        <th scope="col">Proprietario</th>
        <th scope="col">Modelo</th>
        <th scope="col">Ano</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @registros.each do |registro| %>
        <tr>
          <th scope="row"><%= registro.placa %></th>
          <td><%= registro.proprietario %></</td>
          <td><%= registro.modelo %></</td>
          <td><%= registro.ano %></td>
          <td><%= link_to 'Editar registro', edit_placa_path(registro.placa), class: 'btn btn-success' %>
          <%= link_to 'Deletar registro', placa_path(registro.placa), class: 'btn btn-dark', method: :delete %> </td>
        </tr>
      <% end %>
    </tbody>
    </div>
  </table>

app/views/placas/new.html.erb
<%= render 'form' %>